#!/usr/bin/env node

import { Command } from 'commander';
import { writeFile, access } from 'fs/promises';
import * as path from 'path';
import { constants } from 'fs';
import {
  parseConfig,
  processFiles,
  includeTypes,
  compressContent,
  createConfig,
  copyToClipboard,
  promptForQuestion,
  summarizeComponentProps,
} from './utils.js';

const program = new Command();

program
  .name('genprompt')
  .description('Generate a prompt file based on project context')
  .version('1.0.0');

program
  .command('generate')
  .description('Generate the prompt file based on the configuration')
  .option('-c, --config <path>', 'Path to the config file', '.genprompt.json')
  .option('-o, --output <path>', 'Output file (default: clipboard)')
  .option('--compress', 'Compress the content')
  .option(
    '--include-all [pattern]',
    'Include all files matching the pattern in the current directory and subdirectories'
  )
  .option('-f, --files <patterns...>', 'Additional files or patterns to include')
  .option('-q, --question', 'Prompt for a user question after generating the content')
  .option('-e, --editor <editor>', 'Editor to use for writing the question')
  .action(async (options) => {
    const configPath = path.resolve(options.config);

    try {
      const config = await parseConfig(configPath);
      let content = '';

      content += `-- File generated by genprompt --config ${options.config}\n\n`;
      content += '-------- BEGINNING OF SYSTEM CONTEXT INPUT --------\n';

      // Merge include files from config and command line
      let includeFiles = config.include || [];
      if (options.files) {
        includeFiles = includeFiles.concat(options.files);
      }

      if (options.includeAll) {
        const pattern = options.includeAll === true ? '**/*' : options.includeAll;
        includeFiles.push(pattern);
      }

      if (config.includeFiles || options.files) {
        const filesContent = await processFiles(includeFiles);
        content += filesContent;
      }

      if (config.includeTypes) {
        const typesContent = await includeTypes(config.projectRoot || process.cwd());
        content += typesContent;
      }

      if (config.compress || options.compress) {
        content = compressContent(content);
      }

      // Prompt for user's question if the --question flag is present
      if (options.question) {
        const editor = options.editor || config.editor || null;
        const userQuestion = await promptForQuestion(editor);
        content += '\n-------- END OF SYSTEM CONTEXT INPUT --------\n\n';
        content += '-------- BEGINNING OF USER INPUT --------\n\n';
        content += userQuestion;
        content += '\n\n-------- END OF USER INPUT --------';
      } else {
        content += '\n-------- END OF SYSTEM CONTEXT INPUT --------\n\n';
      } 

      // Output to clipboard by default
      const outputPath = options.output ? path.resolve(options.output) : null;
      if (outputPath) {
        await writeFile(outputPath, content);
        console.log(`Prompt file generated at ${outputPath}`);
      } else {
        await copyToClipboard(content);
        console.log('Prompt copied to clipboard.');
      }
    } catch (error) {
      console.error('Error:', error.message);
    }
  });

program
  .command('init')
  .description('Create an initial .genprompt.json configuration file')
  .option('-y, --yes', 'Accept all defaults and skip prompts')
  .option('-f, --force', 'Overwrite existing .genprompt.json file')
  .action(async (options) => {
    const configPath = path.resolve('.genprompt.json');

    try {
      if (!options.force) {
        // Check if .genprompt.json already exists
        await access(configPath, constants.F_OK);
        console.error('.genprompt.json already exists. Use --force to overwrite.');
        process.exit(1);
      }
    } catch {
      // File doesn't exist, proceed to create it
    }

    const config = await createConfig(!options.yes);
    await writeFile(configPath, JSON.stringify(config, null, 2));
    console.log(`Created initial .genprompt.json at ${configPath}`);
  });

  program
  .command("summarize-props")
  .description("Summarize props for React components")
  .option("-f, --files <patterns...>", "Glob patterns for files to analyze")
  .option("-d, --depth <number>", "Maximum depth to resolve nested types", 2)
  .option("-o, --output <path>", "Output file (default: stdout)")
  .action(async (options) => {
    const { files, depth, output } = options;

    if (!files || files.length === 0) {
      console.error("Error: No file patterns provided.");
      process.exit(1);
    }

    try {
      const summary = await summarizeComponentProps(files, parseInt(depth, 10));
      if (output) {
        await writeFile(output, summary);
        console.log(`Props summary written to ${output}`);
      } else {
        console.log(summary);
      }
    } catch (error) {
      console.error("Error during props summary generation:", error.message);
    }
  });

program.parse(process.argv);
